[DEBUG] 2022-12-05 17:06:32.859 [main] Main - Caught test exception
